apiVersion: v1
kind: Service
metadata:
  name: cdevents-demo
  labels:
    {{- include "cdevents-demo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "cdevents-demo.selectorLabels" . | nindent 4 }}
